GET  http://192.168.5.129:3001/v1/checkReferral/onRegistration?player_id=12&inviteCode=34v0jkbpjy72zjsp HTTP/1.1

###
POST http://192.168.5.129:3001/v1/checkReferral/getInviteCode HTTP/1.1
Content-Type: application/x-www-form-urlencoded
x-naz-app-key: 'bsafwesfsdfsdfasfasfasfas'

player_id=11&app_id=1


###
POST http://192.168.5.129:3001/v1/checkReferral/submitRefCode HTTP/1.1
Content-Type: application/x-www-form-urlencoded
x-naz-app-key: 'bsafwesfsdfsdfasfasfasfas'

player_id=12&app_id=1&refcode=jy5tpq85

###
POST http://192.168.5.129:3001/v1/checkReferral/getInviteCode HTTP/1.1
Content-Type: application/x-www-form-urlencoded
x-naz-app-key: bsafwesfsdfsdfasfasfasfas
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjEzMDU1NDIsImRhdGEiOnsic3ViIjoiYXV0aGVudGljYXRpb24iLCJpc3MiOiJodHRwOi8vYmlncGVzYS5jb20iLCJwZXJtaXNzaW9ucyI6ImFsbCIsImlkZW50aXR5Ijp7InNvdXJjZSI6ImxveWFsdHktbnoiLCJwbGF5ZXJJZCI6IjI5IiwiYXBwSWQiOjIsImRhdGUiOiIyMDE5LTA3LTE5VDA3OjE5OjQyLjQ3MVoifX0sImlhdCI6MTU2MzUyMDc4Mn0.sOrZ27DaWJk8eyW2TR-aChctCnT94OJQudCqBoW3ue4

# player_id=11&app_id=1


###
POST http://192.168.5.129:3001/v1/checkReferral/submitRefCode HTTP/1.1
Content-Type: application/x-www-form-urlencoded
x-naz-app-key: bsafwesfsdfsdfasfasfasfas
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjEzMDQ3ODcsImRhdGEiOnsic3ViIjoiYXV0aGVudGljYXRpb24iLCJpc3MiOiJodHRwOi8vYmlncGVzYS5jb20iLCJwZXJtaXNzaW9ucyI6ImFsbCIsImlkZW50aXR5Ijp7InNvdXJjZSI6ImxveWFsdHktbnoiLCJwbGF5ZXJJZCI6IjI3IiwiYXBwSWQiOjIsImRhdGUiOiIyMDE5LTA3LTE5VDA3OjA3OjA3Ljk5OVoifX0sImlhdCI6MTU2MzUyMDAyOH0.RCGhuzqZFelj_hnbPCBvhnacWcG8Amn8kiz4d8j5Mw4

refcode=jy9nz7cx

### 1st player

POST http://192.168.5.129:3001/v1/app/player-register HTTP/1.1
Content-Type: application/x-www-form-urlencoded
x-naz-app-key: bsafwesfsdfsdfasfasfasfas

mobile_number=7208689212&app_player_id=123456789


### 2nd player

POST http://192.168.5.129:3001/v1/app/player-register HTTP/1.1
Content-Type: application/x-www-form-urlencoded
x-naz-app-key: bsafwesfsdfsdfasfasfasfas

mobile_number=7208689212&app_player_id=123456789

### 3nd player

POST http://stg-api.bigpesa.in/v1/ngs/app/player-register HTTP/1.1
Content-Type: application/x-www-form-urlencoded
x-naz-app-key: bsafwesfsdfsdfasfasfasfas

mobile_number=720868921200100&inviteCode=34v02ivjy9q1j2d


# checkReferralController.onRegistration(_player_app_id, _app_id, inviteCode)
# let inviteCode = req.body.inviteCode ? req.body.inviteCode : null;
# var checkReferralController = require('../../../controller/referral/checkReferralController');

### 3nd player

POST http://localhost:3001/v1/checkReferral/claimEvent HTTP/1.1
Content-Type: application/x-www-form-urlencoded
x-naz-app-key: bsafwesfsdfsdfasfasfasfas
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjEzMDU1NDIsImRhdGEiOnsic3ViIjoiYXV0aGVudGljYXRpb24iLCJpc3MiOiJodHRwOi8vYmlncGVzYS5jb20iLCJwZXJtaXNzaW9ucyI6ImFsbCIsImlkZW50aXR5Ijp7InNvdXJjZSI6ImxveWFsdHktbnoiLCJwbGF5ZXJJZCI6IjI5IiwiYXBwSWQiOjIsImRhdGUiOiIyMDE5LTA3LTE5VDA3OjE5OjQyLjQ3MVoifX0sImlhdCI6MTU2MzUyMDc4Mn0.sOrZ27DaWJk8eyW2TR-aChctCnT94OJQudCqBoW3ue4

goal_code=GAMEPLAY